--- 
- hosts: 172.31.30.101 
  become: yes
  tasks:
  - include_tasks: myfiles.yml
  - name: i want install webserver
    apt: 
     name: apache2
     state: present 

  - name: I want to copy static files into ansible nodes side 
    copy:
        src: mystaticfile.html
        dest: /var/www/html/index.html

     