--- 
- hosts: 172.31.30.101 
  become: yes
  tasks:
  - include_tasks: myfiles.yml
  - name: i want install webserver
    apt: 
     name: apache2
     state: present 

  - name: I want to copy static files into ansible nodes side 
    copy:
        src: mystaticfile.html
        dest: /var/www/html/index.html
   
  - name: I want to copy dynamic file into ansible nodes side 
    template:
        src: myindex.j2
        dest: /var/www/html/index.html
    notify:  restartwebserver  

  - name: I want to download files from remote(internet) into nodes side 
    get_url:
       url: https://get.jenkins.io/war-stable/2.332.3/jenkins.war
       dest: /home/ubuntu/jenkins.war
       force_basic_auth: yes       
  - name : i want to create folder
    file:
      path: /home/ubuntu/myfolder
      state: directory
      

  handlers:
  - name: restartwebserver
    service:
       name: apache2 
       state: restarted    