--- 
- hosts: 172.31.30.101 
  become: yes
  tasks:
   - name: I want install git 
     apt:
      name: git
      state: present

   - name: install tree 
     apt:
      name: tree 
      state: present 

   - name: wget
     apt: 
       name: wget 
       state: present      
     